nginx

server {
    listen 80;

    root /usr/share/nginx/index;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /js/ {
        try_files $uri =404;
    }

    location /styles.css {
        try_files $uri =404; 
    }

    error_page 404 /index.html;
    
}